lucassabreu/clockify-cli

.nvimrc, CHANGELOG.md, api/client.go, api/dto/request.go, api/httpClient.go, api/logger.go, cmd/configSet.go, cmd/extras.go, cmd/in.go, cmd/log.go, cmd/logInProgress.go, cmd/root.go, cmd/workspaceUsers.go, go.mod
API URL currently used is not supported anymore
=> (fix): log command fails to retrieve time entries

CHANGELOG.md, api/client.go, api/dto/request.go, cmd/inClone.go, cmd/log.go, cmd/report.go
* (fix): clockify-cli report was not getting all pages
* (added): support to get a time entry by its id and workspace
=> (release): v0.1.7

CHANGELOG.md, cmd/common.go
=> (fix): confirm tasgs on cloning

CHANGELOG.md, api/client.go, api/dto/request.go, cmd/clone.go, cmd/common.go, cmd/configInit.go, cmd/edit.go, cmd/in.go, cmd/manual.go, cmd/projectList.go, cmd/report.go, cmd/root.go, cmd/tags.go, cmd/workspaces.go, reports/timeEntry.go
=> (feat): allow project name

CHANGELOG.md, api/client.go, api/dto/request.go, cmd/tags.go
=> (feat): using v1 to get tags

README.md
=> old readme causing issues

CHANGELOG.md, cmd/common.go, cmd/workspaces.go, reports/workspace.go
- (chg): improvments on workspace command
- (fix): no panic on empty lists
closes #97
=> (release): 0.16.1

CHANGELOG.md, api/client.go, cmd/clone.go, cmd/common.go, cmd/config.go, cmd/edit.go, cmd/in.go, cmd/manual.go, cmd/root.go
=> (fix): none project and incomplete time entry

CHANGELOG.md, cmd/common.go
=> (release): v0.19.2

CHANGELOG.md, ui/ui.go
- (fix): default value must be in the options
closes #113
=> (release): v0.19.5

CHANGELOG.md, api/client.go, api/dto/request.go, cmd/delete.go, cmd/logInProgress.go, cmd/out.go
=> (chg): one call to log in progress

.nvimrc, CHANGELOG.md, api/client.go, api/dto/dto.go, api/dto/request.go, api/httpClient.go, cmd/clone.go, cmd/common.go, cmd/edit.go, cmd/editMultiple.go, cmd/in.go, cmd/manual.go, cmd/markInvoiced.go, cmd/report.go, strhlp/strhlp.go
=> (chore): migrate old api into current ones

CHANGELOG.md, api/client.go, cmd/out.go
=> (fix): 404 error on out

CHANGELOG.md, api/client.go, cmd/clone.go, cmd/common.go, cmd/config.go, cmd/description-completer.go, cmd/edit.go, cmd/editMultiple.go, cmd/in.go, cmd/manual.go, cmd/suggestions.go, go.mod, go.sum, ui/ui.go
=> (feat): autocomplete description

CHANGELOG.md, cmd/description-completer.go, cmd/root.go, ui/ui.go
- (fix): do not println
- (fix): return valid time.Time
- (chg): hide interrupted error
=> (fix): fixes and improviment

CHANGELOG.md, api/client.go, api/dto/request.go, cmd/clone.go, cmd/common.go, cmd/in.go, cmd/projectList.go, cmd/suggestions.go
- fix: do not allow archived projects
- feat: validate time entry when closing it
closes #154 #155
=> (release): v0.30.0

CHANGELOG.md, internal/output/timeEntry.go
=> fix: dont hide description

CHANGELOG.md, api/client.go, api/dto/dto.go, api/dto/request.go, cmd/task.go, cmd/taskAdd.go, cmd/taskDelete.go, cmd/taskDone.go, cmd/taskEdit.go, cmd/taskList.go
=> feat: command to mark tasks as done

CHANGELOG.md, cmd/common.go, cmd/edit.go, go.mod, go.sum, internal/output/timeEntry.go
=> feat: relative time support

CHANGELOG.md, api/client.go, api/dto/request.go, pkg/cmd/time-entry/util/interactive.go
=> issue #196 - dont list inactive tasks

CHANGELOG.md, README.md, pkg/cmd/time-entry/util/interactive.go
=> fix: 200 - error when the user does not have direct access to project

CHANGELOG.md, internal/consoletest/test.go, pkg/cmd/config/init/init_test.go, pkg/cmd/time-entry/report/today/today.go, pkg/cmd/time-entry/report/today/today_test.go, pkg/cmd/time-entry/report/util/report.go
=> fix: report today

api/dto/request.go, api/httpClient.go, pkg/cmd/client/add/add.go, pkg/cmd/client/add/add_test.go, pkg/cmd/client/client.go, pkg/cmd/client/list/list.go, pkg/cmd/client/list/list_test.go, pkg/cmd/project/add/add.go, pkg/cmd/project/add/add_test.go, pkg/cmd/project/list/list.go, pkg/cmd/project/list/list_test.go, pkg/cmd/project/project.go, pkg/cmd/root.go, pkg/cmd/user/me/me.go, pkg/cmd/user/me/me_test.go, pkg/cmd/user/user.go, pkg/cmd/user/user_test.go, pkg/cmd/workspace/workspace.go, pkg/cmd/workspace/workspace_test.go
=> cont. issue: 75

CHANGELOG.md, pkg/cmd/project/add/add_test.go, pkg/cmd/project/list/list_test.go, pkg/cmd/time-entry/report/last-day/last-day.go, pkg/cmd/time-entry/report/last-month/last-month.go, pkg/cmd/time-entry/report/last-week-day/last-week-day.go, pkg/cmd/time-entry/report/last-week/last-week.go, pkg/cmd/time-entry/report/report.go, pkg/cmd/time-entry/report/this-month/this-month.go, pkg/cmd/time-entry/report/this-week/this-week.go, pkg/cmd/time-entry/report/today/today.go, pkg/cmd/time-entry/report/util/report.go, pkg/cmd/time-entry/report/util/report_flag_test.go, pkg/cmd/time-entry/report/util/reportwithrange_test.go, pkg/cmd/time-entry/report/yesterday/yesterday.go, pkg/timehlp/util.go
=> issue #210 - feat: report --billable

CHANGELOG.md, pkg/cmd/task/add/add.go, pkg/cmd/task/add/add_test.go, pkg/cmd/task/delete/delete.go, pkg/cmd/task/delete/delete_test.go, pkg/cmd/task/done/done.go, pkg/cmd/task/done/done_test.go, pkg/cmd/task/edit/edit.go, pkg/cmd/task/edit/edit_test.go, pkg/cmd/task/list/list.go, pkg/cmd/task/list/list_test.go, pkg/cmd/task/task.go, pkg/cmd/task/util/read-flags.go, pkg/cmd/task/util/report.go
=> feat: task add test

CHANGELOG.md, api/client.go, api/client_test.go, api/dto/request.go, internal/mocks/mock_Client.go, pkg/cmd/project/add/add.go, pkg/cmd/project/edit/edit.go, pkg/cmd/project/edit/edit_test.go, pkg/cmd/project/project.go, pkg/cmdutil/flags.go, pkg/cmdutil/flags_test.go, pkg/output/util/template.go, pkg/search/client.go, pkg/search/project.go
=> issue: 214

CHANGELOG.md, pkg/cmd/config/config.go, pkg/cmd/config/init/init.go, pkg/cmd/config/init/init_test.go, pkg/cmd/time-entry/util/interactive.go, pkg/cmdutil/config.go
=> feat: allow-archived-tags param

CHANGELOG.md, api/client.go, pkg/cmd/time-entry/report/today/today_test.go, pkg/cmd/time-entry/report/util/report.go, pkg/cmd/time-entry/report/util/reportwithrange_test.go
=> feat: filter by tags

CHANGELOG.md, internal/mocks/simple_config.go, pkg/cmd/time-entry/edit/edit.go, pkg/cmd/time-entry/edit/edit_test.go, pkg/cmd/time-entry/timeentry.go, pkg/cmd/time-entry/util/fill-with-flags.go
=> fix: clear task when project changes

CHANGELOG.md, api/client_test.go, api/dto/dto.go
=> #230 - fix: project duration may be null

CONTRIBUTING.md, pkg/cmd/time-entry/delete/delete.go
Attempt to close #229, and small details in the CONTRIBUTING.md file.
I'm new to Golang, so any feedback is welcome.
Note: I was not able to build the project on Windows using `make`, I had to do it manually with `go build`. It seems it's because the way the shell variables are set in the Makefile. Also, `grep` and `awk` seem to be required for `make help`, so maybe it's worth mentioning these things somewhere.
=> feat: "delete last" time entry

CHANGELOG.md, pkg/cmd/client/add/add.go, pkg/cmd/completion/completion.go, pkg/cmd/task/quick-add/quick-add.go, pkg/cmd/task/quick-add/quick-add_test.go, pkg/cmd/task/task.go, pkg/cmd/task/util/report.go, pkg/cmd/time-entry/manual/manual.go, pkg/cmd/time-entry/report/this-month/this-month.go, pkg/cmd/time-entry/report/util/report.go, pkg/cmd/time-entry/util/report.go, pkg/output/client/json.go, pkg/output/time-entry/default.go, pkg/output/time-entry/duration.go, pkg/search/task.go, pkg/search/user.go
=> feat: task quick-add

CHANGELOG.md, pkg/ui/ui.go
=> issue/#246 - fix: special chars as spaces

CHANGELOG.md, pkg/cmd/time-entry/report/report.go, pkg/output/util/template.go
=> feat: new until and since functions

CHANGELOG.md, pkg/search/find_test.go, strhlp/strhlp.go
=> fix: find by name with [
